---
apiVersion: v1
data:
  config: '{"address-pools": [{"addresses": ["192.168.1.250-192.168.1.254"], "name":
    "default", "protocol": "layer2"}]}'
kind: ConfigMap
metadata:
  labels:
    app: metallb
  name: metallb-config
  namespace: metallb-system

