---
apiVersion: ark.heptio.com/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: heptio-ark
spec:
  config:
    region: sfo2
    s3Url: https://sfo2.digitaloceanspaces.com
  objectStorage:
    bucket: lbrlabs-ark
    prefix: do
  provider: digitalocean

---
apiVersion: ark.heptio.com/v1
kind: VolumeSnapshotLocation
metadata:
  name: ark-location
  namespace: heptio-ark
spec:
  config:
    provider: digitalocean-blockstore
  provider: digitalocean

