---
apiVersion: ark.heptio.com/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: heptio-ark
spec:
  config:
    region: sfo2
    s3Url: https://sfo2.digitaloceanspaces.com
  objectStorage:
    bucket: lbrlabs
    prefix: do
  provider: aws

---
apiVersion: ark.heptio.com/v1
kind: VolumeSnapshotLocation
metadata:
  name: default
  namespace: heptio-ark
spec:
  config:
    region: sfo2
  provider: digitalocean-blockstore

