{
   "output": "prefixed",
   "tasks": {
      "default": {
         "cmds": [
            "kr8-helpers check-environment",
            {
               "task": "gcloud"
            }
         ]
      },
      "gcloud": {
         "cmds": [
            {
               "task": "gcloud_taskfile"
            },
            "task -d tmp/gcloud generate"
         ],
         "desc": "generate components for gcloud"
      },
      "gcloud_deploy": {
         "cmds": [
            "task -d tmp/gcloud deploy"
         ],
         "desc": "deploy all components for cluster: gcloud"
      },
      "gcloud_dryrun": {
         "cmds": [
            "task -d tmp/gcloud dryrun"
         ],
         "desc": "dryrun all components for cluster: gcloud"
      },
      "gcloud_taskfile": {
         "cmds": [
            "mkdir -p tmp/gcloud",
            "kr8 jsonnet render --cluster gcloud --format yaml templates/task-generate-cluster-parallel.jsonnet > tmp/gcloud/Taskfile.yml"
         ],
         "desc": "generate task file in tmp directory for cluster: gcloud"
      },
      "taskfiles": {
         "cmds": [
            {
               "task": "gcloud_taskfile"
            }
         ],
         "desc": "generate task files for all clusters"
      }
   },
   "version": "2"
}
