{
   "output": "prefixed",
   "tasks": {
      "default": {
         "cmds": [
            "kr8-helpers check-environment",
            {
               "task": "lbr"
            },
            {
               "task": "do"
            }
         ]
      },
      "do": {
         "cmds": [
            {
               "task": "do_taskfile"
            },
            "task -d tmp/do default"
         ],
         "desc": "generate components for do"
      },
      "do_taskfile": {
         "cmds": [
            "mkdir -p tmp/do",
            "kr8 jsonnet render --cluster do --format yaml templates/task-generate-cluster-sequential.jsonnet > tmp/do/Taskfile.yml"
         ],
         "desc": "generate task file in tmp directory for cluster: do"
      },
      "lbr": {
         "cmds": [
            {
               "task": "lbr_taskfile"
            },
            "task -d tmp/lbr default"
         ],
         "desc": "generate components for lbr"
      },
      "lbr_taskfile": {
         "cmds": [
            "mkdir -p tmp/lbr",
            "kr8 jsonnet render --cluster lbr --format yaml templates/task-generate-cluster-sequential.jsonnet > tmp/lbr/Taskfile.yml"
         ],
         "desc": "generate task file in tmp directory for cluster: lbr"
      },
      "taskfiles": {
         "cmds": [
            {
               "task": "lbr_taskfile"
            },
            {
               "task": "do_taskfile"
            }
         ],
         "desc": "generate task files for all clusters"
      }
   },
   "version": "2"
}
