{
   "output": "prefixed",
   "tasks": {
      "default": {
         "cmds": [
            "kr8-helpers check-environment",
            {
               "task": "do"
            },
            {
               "task": "gcloud"
            },
            {
               "task": "kops"
            },
            {
               "task": "minikube"
            }
         ]
      },
      "do": {
         "cmds": [
            {
               "task": "do_taskfile"
            },
            "task -d tmp/do generate"
         ],
         "desc": "generate components for do"
      },
      "do_deploy": {
         "cmds": [
            "task -d tmp/do deploy"
         ],
         "desc": "deploy all components for cluster: do"
      },
      "do_dryrun": {
         "cmds": [
            "task -d tmp/do dryrun"
         ],
         "desc": "dryrun all components for cluster: do"
      },
      "do_taskfile": {
         "cmds": [
            "mkdir -p tmp/do",
            "kr8 jsonnet render --cluster do --format yaml templates/task-generate-cluster-parallel.jsonnet > tmp/do/Taskfile.yml"
         ],
         "desc": "generate task file in tmp directory for cluster: do"
      },
      "gcloud": {
         "cmds": [
            {
               "task": "gcloud_taskfile"
            },
            "task -d tmp/gcloud generate"
         ],
         "desc": "generate components for gcloud"
      },
      "gcloud_deploy": {
         "cmds": [
            "task -d tmp/gcloud deploy"
         ],
         "desc": "deploy all components for cluster: gcloud"
      },
      "gcloud_dryrun": {
         "cmds": [
            "task -d tmp/gcloud dryrun"
         ],
         "desc": "dryrun all components for cluster: gcloud"
      },
      "gcloud_taskfile": {
         "cmds": [
            "mkdir -p tmp/gcloud",
            "kr8 jsonnet render --cluster gcloud --format yaml templates/task-generate-cluster-parallel.jsonnet > tmp/gcloud/Taskfile.yml"
         ],
         "desc": "generate task file in tmp directory for cluster: gcloud"
      },
      "kops": {
         "cmds": [
            {
               "task": "kops_taskfile"
            },
            "task -d tmp/kops generate"
         ],
         "desc": "generate components for kops"
      },
      "kops_deploy": {
         "cmds": [
            "task -d tmp/kops deploy"
         ],
         "desc": "deploy all components for cluster: kops"
      },
      "kops_dryrun": {
         "cmds": [
            "task -d tmp/kops dryrun"
         ],
         "desc": "dryrun all components for cluster: kops"
      },
      "kops_taskfile": {
         "cmds": [
            "mkdir -p tmp/kops",
            "kr8 jsonnet render --cluster kops --format yaml templates/task-generate-cluster-parallel.jsonnet > tmp/kops/Taskfile.yml"
         ],
         "desc": "generate task file in tmp directory for cluster: kops"
      },
      "minikube": {
         "cmds": [
            {
               "task": "minikube_taskfile"
            },
            "task -d tmp/minikube generate"
         ],
         "desc": "generate components for minikube"
      },
      "minikube_deploy": {
         "cmds": [
            "task -d tmp/minikube deploy"
         ],
         "desc": "deploy all components for cluster: minikube"
      },
      "minikube_dryrun": {
         "cmds": [
            "task -d tmp/minikube dryrun"
         ],
         "desc": "dryrun all components for cluster: minikube"
      },
      "minikube_taskfile": {
         "cmds": [
            "mkdir -p tmp/minikube",
            "kr8 jsonnet render --cluster minikube --format yaml templates/task-generate-cluster-parallel.jsonnet > tmp/minikube/Taskfile.yml"
         ],
         "desc": "generate task file in tmp directory for cluster: minikube"
      },
      "taskfiles": {
         "cmds": [
            {
               "task": "do_taskfile"
            },
            {
               "task": "gcloud_taskfile"
            },
            {
               "task": "kops_taskfile"
            },
            {
               "task": "minikube_taskfile"
            }
         ],
         "desc": "generate task files for all clusters"
      }
   },
   "version": "2"
}
