---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kiam
    chart: kiam-1.2.0
    component: agent
    heritage: Tiller
    release: kiam
  name: kiam-agent

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kiam
    chart: kiam-1.2.0
    component: server
    heritage: Tiller
    release: kiam
  name: kiam-server

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: kiam
    chart: kiam-1.2.0
    component: server
    heritage: Tiller
    release: kiam
  name: kiam-server
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - watch
  - get
  - list

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: kiam
    chart: kiam-1.2.0
    component: server
    heritage: Tiller
    release: kiam
  name: kiam-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kiam-server
subjects:
- kind: ServiceAccount
  name: kiam-server
  namespace: kube-system

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kiam
    chart: kiam-1.2.0
    component: server
    heritage: Tiller
    release: kiam
  name: kiam-server
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: kiam
    component: server
    release: kiam

---
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  labels:
    app: kiam
    chart: kiam-1.2.0
    component: agent
    heritage: Tiller
    release: kiam
  name: kiam-agent
spec:
  selector:
    matchLabels:
      app: kiam
      component: agent
      release: kiam
  template:
    metadata:
      labels:
        app: kiam
        component: agent
        release: kiam
    spec:
      containers:
      - args:
        - --iptables
        - --host-interface=cali+
        - --json-log
        - --level=info
        - --port=8181
        - --cert=/etc/kiam/tls/cert
        - --key=/etc/kiam/tls/key
        - --ca=/etc/kiam/tls/ca
        - --server-address=kiam-server:443
        - --prometheus-listen-addr=0.0.0.0:9620
        - --prometheus-sync-interval=5s
        - --gateway-timeout-creation=1s
        command:
        - /agent
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: quay.io/uswitch/kiam:v2.8
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /ping
            port: 8181
          initialDelaySeconds: 3
          periodSeconds: 3
        name: kiam-agent
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/kiam/tls
          name: tls
        - mountPath: /var/run/xtables.lock
          name: xtables
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/node: ""
      serviceAccountName: kiam-agent
      tolerations:
      - operator: Exists
      volumes:
      - name: tls
        secret:
          secretName: kiam-agent
      - hostPath:
          path: /run/xtables.lock
        name: xtables
  updateStrategy:
    type: RollingUpdate

---
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  labels:
    app: kiam
    chart: kiam-1.2.0
    component: server
    heritage: Tiller
    release: kiam
  name: kiam-server
spec:
  selector:
    matchLabels:
      app: kiam
      component: server
      release: kiam
  template:
    metadata:
      labels:
        app: kiam
        component: server
        release: kiam
    spec:
      containers:
      - args:
        - --json-log
        - --level=info
        - --bind=0.0.0.0:443
        - --cert=/etc/kiam/tls/cert
        - --key=/etc/kiam/tls/key
        - --ca=/etc/kiam/tls/ca
        - --role-base-arn-autodetect
        - --session-duration=15m
        - --sync=1m
        - --prometheus-listen-addr=0.0.0.0:9620
        - --prometheus-sync-interval=5s
        command:
        - /server
        image: quay.io/uswitch/kiam:v2.8
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /health
            - --cert=/etc/kiam/tls/cert
            - --key=/etc/kiam/tls/key
            - --ca=/etc/kiam/tls/ca
            - --server-address=localhost:443
            - --server-address-refresh=2s
            - --timeout=5s
            - --gateway-timeout-creation=1s
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
        name: kiam-server
        readinessProbe:
          exec:
            command:
            - /health
            - --cert=/etc/kiam/tls/cert
            - --key=/etc/kiam/tls/key
            - --ca=/etc/kiam/tls/ca
            - --server-address=localhost:443
            - --server-address-refresh=2s
            - --timeout=5s
            - --gateway-timeout-creation=1s
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /etc/kiam/tls
          name: tls
        - mountPath: /etc/ssl/certs
          name: ssl-certs
          readOnly: true
      hostNetwork: false
      nodeSelector:
        node-role.kubernetes.io/master: ""
      serviceAccountName: kiam-server
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
        value: ""
      volumes:
      - name: tls
        secret:
          secretName: kiam-server
      - hostPath:
          path: /etc/pki/ca-trust/extracted/pem
        name: ssl-certs
  updateStrategy:
    type: RollingUpdate

