---
apiVersion: ark.heptio.com/v1
kind: BackupStorageLocation
metadata:
  name: ark-backup-do
  namespace: heptio-ark
spec:
  config:
    region: sfo2
    s3Url: https://sfo2.digitaloceanspaces.com
  objectStorage:
    bucket: lbrlabs-ark
  provider: aws

