version: 2

vars:
  KR8_COMPONENT: psp

tasks:
  fetch:
    desc: "fetch component dependencies"

  generate:
    desc: "generate"
    cmds:
      - KR8_COMPONENT={{.KR8_COMPONENT}} kr8-helpers clean-output
      - KR8_COMPONENT={{.KR8_COMPONENT}} kr8-helpers jsonnet-render clusterroles.jsonnet policies.jsonnet
