---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ark
  namespace: heptio-ark
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8085"
        prometheus.io/scrape: "true"
      labels:
        component: ark
    spec:
      containers:
      - args:
        - server
        command:
        - /ark
        env:
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /credentials/cloud
        - name: ARK_SCRATCH_DIR
          value: /scratch
        image: gcr.io/heptio-images/ark:latest
        name: ark
        volumeMounts:
        - mountPath: /credentials
          name: cloud-credentials
        - mountPath: /plugins
          name: plugins
        - mountPath: /scratch
          name: scratch
      restartPolicy: Always
      serviceAccountName: ark
      volumes:
      - name: cloud-credentials
        secret:
          secretName: cloud-credentials
      - name: plugins
      - name: scratch

