---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ark
  namespace: heptio-ark
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: ""
        prometheus.io/path: /metrics
        prometheus.io/port: "8085"
        prometheus.io/scrape: "true"
      labels:
        component: ark
    spec:
      containers:
      - args:
        - server
        - --default-volume-snapshot-locations=digitalocean-blockstore:default
        command:
        - /ark
        env:
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /credentials/cloud
        - name: DIGITALOCEAN_TOKEN
          valueFrom:
            secretKeyRef:
              key: digitalocean_token
              name: cloud-credentials
        image: gcr.io/heptio-images/ark:v0.10.0
        name: ark
        ports:
        - containerPort: 8085
          name: metrics
        volumeMounts:
        - mountPath: /plugins
          name: plugins
        - mountPath: /credentials
          name: cloud-credentials
      initContainers:
      - image: gcr.io/stackpoint-public/ark-blockstore-digitalocean:latest
        name: ark-blockstore-digitalocean
        volumeMounts:
        - mountPath: /target
          name: plugins
      restartPolicy: Always
      serviceAccountName: ark
      volumes:
      - name: plugins
      - name: cloud-credentials
        secret:
          secretName: cloud-credentials

